### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by sonychoudhary** [SenagasettiRamesh/cordova-plugin-sms-retriever-api#2]
i have generated the hashcode and the app is reading the message but just as the message arrives the app crash giving some null error in log file
957 E AndroidRuntime: FATAL EXCEPTION: main
03-12 16:22:09.234 19957 19957 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.cordova.plugin.android.smsretriever.smsreceiverapi: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3413)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.-wrap18(Unknown Source:0)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7000)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at com.cordova.plugin.android.smsretriever.smsreceiverapi.onReceive(smsreceiverapi.java:37)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3406)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: ... 8 more

**Comment by sonychoudhary** [comment]
i have generated the hashcode and the app is reading the message but just as the message arrives the app crash giving some null error in log file
957 E AndroidRuntime: FATAL EXCEPTION: main
03-12 16:22:09.234 19957 19957 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.cordova.plugin.android.smsretriever.smsreceiverapi: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3413)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.-wrap18(Unknown Source:0)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7000)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at com.cordova.plugin.android.smsretriever.smsreceiverapi.onReceive(smsreceiverapi.java:37)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3406)
03-12 16:22:09.234 19957 19957 E AndroidRuntime: ... 8 more

**Comment by SenagasettiRamesh** [comment]
Missed it. Handled the issue mentioned. Please use it if you still have this issue.
